### ISSUE TITLE
Perspective camera controls

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#103]
As a user, I want to be able to move the camera around in the visualization area, so that I can closely inspect specific groups of markers from different angles, or get a better angle to more easily select one of interest.

## Definition of Done
- [x] Camera has flight controls (forward, backward, left, right, up, down)
- [x] Camera has look controls (look left, right, up, down)
- [x] Controls support right- and left-handed use

## Tasks
- [x] #104
- [x] #105
