### ISSUE TITLE
Main menu button

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#129]
As a user, I want to easily be able to find Movilo's main menu where a controls help cheatsheet and other extended options may be found, so that I can quickly and easily learn how to use Movilo for the first time, and look up features if I forget about them.

## Definition of Done
- [ ] Main menu button appears in the UI immediately to the right of the Movilo logo and above the rendering area so it may be easily found and has plenty of space to open into the rendering area
- [x] Menu button is styled as a "hamburger button" so new users can intuitively identify it as the main menu
- [x] Controls help cheatsheet gives summary of camera fly & look controls, marker selection controls, instructions for tri-selecting markers to compute angle, suggested gait event controls, and manual frame selection and cropping

## Tasks
- [x] #142
- [x] #143

**Comment by ConnorJacksonBSU** [comment]
worked on extensively through the weekend of sprint 3. Waiting on further reviews and pull request to be approved. last worked on 10/27

**Comment by PTLux1517** [comment]
Our definition of done has evolved now that we are producing both help images (in the menu) and more detailed text (in the documentation). Suggested gait event controls help will be added in sprint 4, and manual frame selection will be discussed in text, as its ordinary use is intuitive enough and its more nuanced features are better captured in a text description.
