### ISSUE TITLE
Set up initial CI

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#13]
As a developer, I want continuous integration to run when I push my code, so that my code will be built, tested, and safely deployed.

## Definition of Done
- [x] CI workflow runs without errors
- [x] Install, build, and test are done through `install.sh`, `build.sh`, and `test.sh` with appropriate exit statuses
- [x] `README.md` has a badge indicating the status of the last CI run
- [x] After successful run, page is deployed to https://ptlux1517.github.io/Movilo (can be changed later)

## Tasks
- [x] #19
- [x] #20
