### ISSUE TITLE
Display angle on tri-selection

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#130]
As a user, I want the angle between 3 markers I select to automatically be displayed alongside the marker metadata, so that it's easy and intuitive for me to take joint angle measurements.

## Definition of Done
- [x] Upon the user selecting 3 markers, an array containing these markers' Point3D coordinates (in their order selected) are passed to the Calculations.computeAngle function, and on return, the computed angle measurement is added to the top of the metadata output area
- [x] Angle computations that detect an error condition and return NaN display a more user-friendly output, such as "missing data"
- [x] Angle output identifies the measured joint by its marker label, e.g., "LKJC Angle:" for the hip-knee-ankle angle (where LKJC is the Vicon label that stands for left knee joint center)

## Tasks
- [x] #161 
- [x] #162
