### ISSUE TITLE
Marker Selection

### ISSUE THREAD

**Issue by vpzomtrrfrt** [cs481-ekh/f22-viz-kids#136]
As a user, I want to be able to click to select markers, so that I can view metadata and calculations

## Definition of Done
- [ ] Markers can be selected by clicking
- [ ] Selected markers are highlighted with color
- [ ] Selected markers are shown in the metadata area

## Tasks
- [ ] Allow selecting markers
- [ ] Display selected marker metadata
