### ISSUE TITLE
Set up build system & page setup

### ISSUE THREAD

**Issue by vpzomtrrfrt** [cs481-ekh/f22-viz-kids#14]
As a developer, I want to have a build system and page structure, so that I can add features to the project

## Definition of Done
- [x] Build setup exists
- [x] Page framework is functional
- [x] Basic usage of THREE is demonstrated

## Tasks
- [x] #15
- [x] #16
- [x] #25
- [x] #35
