### ISSUE TITLE
SDP logo

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#156]
As a user, I want to see the SDP logo prominently displayed in Movilo, so that I click on it to find out where to go to sponsor another app.

## Definition of Done
- [x] SDP logo appears beneath the metadata output area
- [x] SDP info opens in the popup area (above the viz area) on logo click
- [x] Link to sponsor info page opens in a new tab

## Tasks
- [x] #157
- [x] #158
