### ISSUE TITLE
Create wireframe Prototype

### ISSUE THREAD

**Issue by ConnorJacksonBSU** [cs481-ekh/f22-viz-kids#17]
As a developer, I want to be able to get a general rough draft visual of what the program will look, so that I can get a better idea of what I am working towards

## Definition of Done
- [x] Prototype linked in README
- [x] Wireframe project created
- [x] Main Layout of App designed
## Tasks
- [x] #22 
- [x] #33
- [x] #34
