### ISSUE TITLE
Body segments

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#174]
As a user, I want Movilo to visualize body segments from my data, so that I can more easily identify joint markers and visually inspect important joint angles in the trial animation.

## Definition of Done
- [x] Body segments for different models are able to be defined in a config file using pairs of marker labels for each segment
- [x] Body segments are animated and remain attached to their respective markers at all times
- [x] Individual body segments disappear during frames containing bad marker data at either end of the segment
- [x] Body segments may be toggled on and off in the main menu

## Tasks
- [x] #184
- [x] #185
- [x] #186
