### ISSUE TITLE
Add basic implementation for torque visualization

### ISSUE THREAD

**Issue by wkenny80** [cs481-ekh/f22-viz-kids#194]
As a Developer, I want to add x y and z torque for the potential visualization of torque, so that a user can visualize torque specs.

## Definition of Done
- [ ] Display of meta data on selection view
- [ ] parse data correctly
- [ ] test parser

## Tasks
- [ ] Add basic implementation for torque visualization

**Comment by PTLux1517** [comment]
We were going to attempt this as a stretch goal after finishing the repository readme, but ran out of time.
