### ISSUE TITLE
Desktop shortcut and icon

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#208]
As a user, I want to be able to launch Movilo from my desktop, so that I don't need to have internet access to use it.

## Definition of Done
- [ ] Desktop shortcut works for Windows and opens the local index.html in the browser
- [ ] The shortcut has a custom icon

## Tasks
- [ ] Create desktop shortcut
- [ ] Design Movilo icon

**Comment by PTLux1517** [comment]
We initially thought a local build of Movilo might be useful, but later determined it would make more sense to access it over the internet on the SDP server. The local approach was not required by our sponsor, could be fragile if they don't follow precise installation instructions, and would not be as flexible for future updates.
