### ISSUE TITLE
Repository readme

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#210]
As a developer, I want to provide a proper readme, so that I future collaborators have a greater understanding of the project.

## Definition of Done
- [x] The project is thoroughly covered and described.
- [x] All information needed is added.

## Tasks
- [x]  add read me description
