### ISSUE TITLE
Parse marker file data

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#46]
As a student visiting the COBR lab, I want the marker data file I upload to Movilo to be read/parsed, so that the app can use it to show me a visualization.

## Definition of Done
- [x] Parser module exports a parseMarkerFileData function that accepts a File object as input, and returns a Promise<MarkerFileData> object
- [x] Any Error object returned within a rejected Promise should contain information about the error
- [x] Any MarkerFileData object returned within within a resolved Promise should contain all data from the trial (marker 3D coordinates, marker labels, and frames with times, all correctly associated)

## Tasks
- [x] #48
- [x] #66
- [x] #49
