### ISSUE TITLE
Parse force file data

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#50]
As a student visiting the COBR lab, I want the force plate data file I upload to Movilo to be read/parsed, so that the app can use it to show me a visualization.

## Definition of Done
- [x] Parser module exports a parseForceFileData function that accepts a File object as input, and returns a Promise<ForceFileData> object
- [x] Any Error object returned within a rejected Promise should contain information about the error
- [x] Any ForceFileData object returned within a resolved Promise should contain all data from the trial (vector position, vector component velocities, torque, and frames with times, all correctly associated)

## Tasks
- [x] #51
- [x] #73
- [x] #52
