### ISSUE TITLE
User-friendly upload/parse error alerts

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#89]
As a user, I want Movilo to give me descriptive error messages in the UI when I upload the wrong files, so that I can know what went wrong and how to properly upload my marker and force plate data files.

## Definition of Done
- [x] Extensions beyond .tsv .csv .txt .mot cause an alert detailing expected file types
- [x] TSV/CSV data that does not exactly match the output from Vicon Nexus or OpenSim causes an alert that specifies the expected format
- [x] File name text next to upload button doesn't show the name of an invalid file if one is selected

## Tasks
- [x] #94
- [x] #95
