### ISSUE TITLE
Render object for each frame demonstrating force data. 

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#90]
As a user, I want Movilo to visualize my force plate data, so that I can easily see its relative magnitude and direction imposed on the markers as the subject steps on the force plates.

## Definition of Done
- [x] Ground reaction force (GRF) vectors are rendered as lines or arrows
- [x] GRF vectors are different in length depending on their magnitude, and the max length never exceeds the height of the subject in ordinary, non-faulty data
- [x] Renderer only renders vector data that is non-zero (i.e., when a foot is in contact with the plate)

## Tasks
- [x] #117 
- [x] #119
