### ISSUE TITLE
Text-based timeline controls and info area

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#91]
As a user, I want to be able to see and manipulate the current, start, and end frame number, so that I can jump to a specific frame or select a start and end frame to crop the animation loop. This will also expose the collected time data to me where the timeline track otherwise would not.

## Definition of Done
- [ ] Frame numbers are all editable, but times are not (they are only there for display)
- [ ] Start and end frames/times are correctly set from the values in parsed MarkerFileData
- [ ] Current frame/time is initially set to 0 and 0.0 after file(s) are loaded, but once they are manually changed, they don't spontaneously jump back to 0

## Tasks
- [ ] #121 
- [ ] Task 2
