### ISSUE TITLE
Track-based timeline controls

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#92]
As a user, I want to be able to manipulate the current animation frame number via a timeline track, and play or pause the animation via a play button, so that I can visually jump to a specific frame in the animation loop, or stop it to analyze the data at that point.

## Definition of Done
- [x] Play button toggles between pause and back with relevant icons or CSS styles
- [x] Min and max of range are correctly set from the first and last frame values in parsed MarkerFileData
- [x] Current value (frame) is initially set to 0 after file(s) are loaded, but once it is manually changed, it doesn't spontaneously jump back to 0
- [x] Track styling is compatible with Chrome, Firefox, and Edge

## Tasks
- [x] #113 
- [x] #114
