### ISSUE TITLE
Ground plane grid and axis helper

### ISSUE THREAD

**Issue by PTLux1517** [cs481-ekh/f22-viz-kids#96]
As a user, I want Movilo to show the ground as a grid and have the axes labeled, so that I can properly interpret the spacial orientation of numerical marker metadata.

## Definition of Done
- [x] Ground plane appears in the scene, is subtle enough to not distract from the markers, and extends enough to cover the full capture volume
- [x] Axis helper appears in the scene, follows the camera, and is out of the way
- [x] Axis helper shows COBR's coordinate system, so THREE's different coordinate system is hidden from the user
- [x] Both ground and axis helper are rendered immediately (without waiting for file upload)

## Tasks
- [x] #97
- [x] #98
